### ISSUE TITLE
SRD example?

### ISSUE THREAD

**Issue by eric-haibin-lin** [aws/libfabric#2]
I noticed that EFA support three types of endpoints:
- FI_EP_DGRAM, 
- FI_EP_RDM, and
- SRD

https://github.com/aws/aws-ofi-nccl/ is an example of using FI_EP_RDM. Is there any code example using SRD?

**Comment by rajachan** [comment]
Haibin - EFA supports the standard RDM (reliable datagram) and DGRAM (unreliable datagram) endpoint types in libfabric. SRD, the underlying transport protocol for EFA, is exposed to libfabric applications via the `FI_EP_RDM` endpoint type. Like you noticed, NCCL uses SRD through this endpoint type as well.

**Comment by eric-haibin-lin** [comment]
Noted. Thanks!
