### ISSUE TITLE
 Is polling the only way to read from the completion queue with efa?

### ISSUE THREAD

**Issue by VoVAllen** [aws/libfabric#4]
Hi,

I'm wondering whether polling is the only method if I would like to read from a completion queue with efa. Is there other wait set supported now?

Thanks.

**Comment by zhngaj** [comment]
Thanks for opening the issue.
Yes, EFA currently only supports polling mode. The wait_obj has to be FI_WAIT_NONE when opening cq.
https://github.com/aws/libfabric/blob/master/prov/efa/src/efa_cq.c#L266
https://github.com/aws/libfabric/blob/master/prov/efa/src/rxr/rxr_cq.c#L909

**Comment by VoVAllen** [comment]
Thanks!
