### ISSUE TITLE
Multiple endpoint VS one endpoint using RDM on EFA

### ISSUE THREAD

**Issue by VoVAllen** [aws/libfabric#5]
Hi,

I'm trying to using libfabric to do distributed DL training tasks, which means one machine will need to communicate with multiple other machines. Therefore for the implementation, shall I use multiple libfabric endpoints(for each peer connection) or one libfabric endpoints to communicate with them all? Will there be any performance issue/advantage of them? Which one is used in the MPI implementation over EFA?

Thanks.

**Comment by zhngaj** [comment]
EFA supports RDM endpoint which provides a reliable, connectionless data transfer service.
If you use multiple endpoints for each peer connection, that basically means you mimic connection-oriented data transfer on top of RDM. As the scale increases, you might need up having N² endpoints, where N is #peer. Please note that each endpoint will have dedicated resource associated to it. So lots of resources will be created unnecessarily and wastefully. 

For MPI implementation, it uses one endpoint communicating with all other peers. Each MPI process creates an endpoint, and talks to all other MPI processes with that endpoint.

**Comment by VoVAllen** [comment]
Thanks for your instruction!
