### ISSUE TITLE
Availability of EFA for CentOS/AArch64

### ISSUE THREAD

**Issue by afernandezody** [aws/libfabric#7]
Hello,
Maybe this is a silly question but something is not making sense to me. I'm proceeding with
```
./configure --prefix=/opt/EFA --enable-efa=yes
make
sudo make install
```
This configures, compiles and builds without any problem. However, the system doesn't have efa.ko and that brings my question: Wouldn't the kernel be needed to complete the previously mentioned actions? I'm obviously missing something because I was expecting an error that never materialized. Thanks.

**Comment by rajachan** [comment]
@afernandezody the libfabric configuration script checks for the availabiltity of the rdma-core libraries to decide if the EFA provider should be compiled in. At runtime, if the EFA kernel driver (efa.ko) is not loaded, the provider will not be available (say, when you run the `fi_info -l` command or via the API when you query for providers with fi_getinfo()).

In your case, I'm assuming you have the rdma-core libraries installed, which is why configuration succeeded.  You can verify this in the configure logs as well:

```
$ grep ibv_open_device config.log
configure:23077: checking for ibv_open_device in -libverbs
configure:25131: checking for ibv_open_device in -libverbs
ac_cv_lib_ibverbs_ibv_open_device=yes
```

**Comment by afernandezody** [comment]
Hi @**rajachan**, 
That makes sense (and sort of in line with what I was thinking after opening the thread). However, and this is kind of the second part of my question, why is this not theoretically available for a combination CentOS8-arm64 (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/efa.html#efa-instance-types)? Is there any technical reason or could it be simply because it hasn't been tested? Thank you.

**Comment by afernandezody** [comment]
As far as initial testing, it didn't exhibit any problem using EFA with CentOS/AArch64. A full analysis would probably require launching two clusters with thousands of cores and comparing performance with and without EFA but we don't have those data yet.

**Comment by rwespetal** [comment]
I apologize for the delay here. There isn't a technical reason CentOS 8 and ARM is not supported, there is a kernel fix that is needed for CentOS 8, otherwise you may experience kernel panics when using EFA. We are working on determining whether that backport is done and can follow up once we know.

**Comment by rwespetal** [comment]
The latest CentOS kernel, kernel-4.18.0-240.22.1.el8_3.x86_64, has the fix needed for EFA + ARM support. We hope to update our public documentation soon for this, please let us know if you have issues.
